FROM confluentinc/cp-server-connect-base:6.2.0

RUN wget https://repo1.maven.org/maven2/io/debezium/debezium-connector-sqlserver/1.7.0.Alpha1/debezium-connector-sqlserver-1.7.0.Alpha1-plugin.tar.gz \
    && tar -xvf ./debezium-connector-sqlserver-1.7.0.Alpha1-plugin.tar.gz -C /usr/share/java/

