# Default template
---
type: post
layout: "post"
title: ${1}
author: nielsb
date: ${2}
comments: true
highlight: true
draft: true
tags:
  -
description: ${3}
keywords:
  -   
---


<!--more-->



![](/images/posts/<image_name_incl_ext>)

**Figure 1:** **


## ~ Finally

If you have comments, questions etc., please comment on this post or [ping][ma] me.

[ma]: mailto:niels.it.berglund@gmail.com
[mp]: https://blog.acolyer.org
[iq]: https://www.infoq.com/
[ew]: http://sqlonice.com/
[re]: http://blog.revolutionanalytics.com
[sqsk]: https://www.sqlskills.com


<!--
  post reference
  [pkg1]: {{< relref "" >}}
-->  


<!--
[series1]: <> [SQL Server R Services](/series/sql_server_2k16_r_services)
[series2]: <> [Install R Packages in SQL Server ML Services](/series/sql_server_ml_services_install_packages)
[series3]: <> [sp_execute_external_script and SQL Server Compute Context](/series/spees_and_sql_compute_context)
-->

<!--
[findstr]: <> findstr /I \<word_to_find\> *
-->
