SET ACCEPT_EULA=Y
SET CLUSTER_PLATFORM=minikube

SET CLUSTER_COMPUTE_POOL_REPLICAS=1
SET CLUSTER_STORAGE_POOL_REPLICAS=1 
SET CLUSTER_DATA_POOL_REPLICAS=1

SET USE_PERSISTENT_VOLUME=false

SET CONTROLLER_USERNAME=controlleruser
SET CONTROLLER_PASSWORD=password1234$
SET KNOX_PASSWORD=password1234$
SET MSSQL_SA_PASSWORD=password1234$

SET DOCKER_REGISTRY=private-repo.microsoft.com
SET DOCKER_REPOSITORY=mssql-private-preview
SET DOCKER_USERNAME=<some_username>
SET DOCKER_PASSWORD=<some_password>
SET DOCKER_EMAIL=<some_email>
SET DOCKER_PRIVATE_REGISTRY=1