SET ACCEPT_EULA=Y
SET CLUSTER_PLATFORM=aks

SET CONTROLLER_USERNAME=admin
SET CONTROLLER_PASSWORD=password1234$
SET KNOX_PASSWORD=password1234$
SET MSSQL_SA_PASSWORD=password1234$

SET DOCKER_REGISTRY=private-repo.microsoft.com
SET DOCKER_REPOSITORY=mssql-private-preview
SET DOCKER_USERNAME=niels.berglund@derivco.co.za
SET DOCKER_PASSWORD=4f38g49ppf3g
SET DOCKER_EMAIL=niels.berglund@derivco.co.za
SET DOCKER_PRIVATE_REGISTRY="1"