version: '3.4'

services:
  dbz-eventhub:
    image: confluentinc/cp-server-connect-base:latest
    container_name: dbz-eventhub-cont
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "dbzeventhubs.servicebus.windows.net:9093"
      CONNECT_REST_ADVERTISED_HOST_NAME: 'dbz-eventhub-1'
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: dbz-eventhub-1
      
      CONNECT_CONFIG_STORAGE_TOPIC: configs
      CONNECT_OFFSET_STORAGE_TOPIC: offsets
      CONNECT_STATUS_STORAGE_TOPIC: status
      
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      
      # connect worker
      CONNECT_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_SASL_MECHANISM: PLAIN
      CONNECT_SASL_JAAS_CONFIG: "<JAAS-config-string>;"

      # connect producer
      CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_PRODUCER_SASL_MECHANISM: PLAIN
      CONNECT_PRODUCER_SASL_JAAS_CONFIG: "<JAAS-config-string>;"
      
    command: 
      - bash 
      - -c 
      - |
        echo "Installing connector plugins"
        confluent-hub install --no-prompt debezium/debezium-connector-sqlserver:latest
        #
        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run & 
        #
        sleep infinity      

